#!/usr/bin/env bash

branch=${1}
if [[ -z "${branch}" ]]; then
    echo "Must specify a branch name"
    exit 1
fi

UPSTREAM_STATUS=1
ORIGIN_STATUS=1

if git remote | grep upstream > /dev/null; then
    git ls-remote --exit-code --heads upstream ${branch} > /dev/null
    UPSTREAM_STATUS=$?
    if [[ ${UPSTREAM_STATUS} -eq 0 ]]; then
        git push --delete upstream ${branch}
    fi
fi

git ls-remote --exit-code --heads origin ${branch} > /dev/null
ORIGIN_STATUS=$?
if [[ ${ORIGIN_STATUS} -eq 0 ]]; then
    git push --delete origin ${branch}
fi

if ! git branch --delete ${branch}; then
    echo
    printf "Do you really want to delete branch '${branch}'? (y/n): "
    read -r delete_branch

    if [[ "${delete_branch}" == "y" ]]; then
        echo
        git branch -D ${branch}
    else
        echo "did not force delete"
    fi
fi

if [[ ${UPSTREAM_STATUS} -eq 0 || ${ORIGIN_STATUS} -eq 0 ]]; then
    echo
    echo "Remote branches deleted:"
fi

if [[ ${UPSTREAM_STATUS} -eq 0 ]]; then
    printf "%-40s\n" "    upstream/${branch}"
fi

if [[ ${ORIGIN_STATUS} -eq 0 ]]; then
    printf "%-40s\n" "    origin/${branch}"
fi
