#!/usr/bin/env zsh
branch=${1}
if [[ -z "${branch}" ]]; then
    echo "Must specify a branch name"
    return 1
fi

git show-ref --verify --quiet "refs/heads/${branch}" 2> /dev/null
branch_status=$?
if [[ branch_status -eq 1 ]] ; then
    echo "Branch '${branch}' does not exist"
    return 1
elif [[ branch_status -ne 0 ]]; then
    echo "Could not cleanup branch '${branch}'"
    return 1
fi

git push --delete origin ${branch}
git branch -D ${branch}
