#!/usr/bin/env bash

session_name=${1}

if [[ -z ${session_name} ]]; then
    echo "A session name must be provided."
    exit 1
else
    tmuxp load -s ${session_name} ~/workspace/.tmux/code-session.yaml
fi

