#!/usr/bin/env bash

remote=origin

upstream_exists=$(git remote | grep upstream | wc -l | awk '{print $1}')
if [[ ${upstream_exists} -eq 1 ]]; then
    remote=upstream
fi

default_branch=$(git remote show ${remote} | grep HEAD | cut -d ':' -f 2 | tr -d '[:space:]')

git pull --rebase ${remote} ${default_branch}
