#!/usr/bin/env bash

playground_dir=~/workspace/go_playground
playground_name=$1

if [[ -z "${playground_name}" ]]; then
    echo "Must specify a playground name"
    exit 1
fi

new_playground=${playground_dir}/${playground_name}
mkdir ${new_playground}
mkdir_status=$?

if [[ mkdir_status -ne 0 ]]; then
    echo "Failed to create playground '${playground_name}'"
    exit 1
fi

printf 'package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, 世界")
}
' > ${new_playground}/main.go


current_dir=$(pwd)
cd ${new_playground}
lvim
cd ${current_dir}
