#!/usr/bin/env zsh

playground_dir=${SOME_DIR}
playground_name=$1

if [[ -z "${playground_name}" ]]; then
    echo "Must specify a playground name"
    return 1
fi

new_playground=${playground_dir}/${playground_name}
mkdir ${new_playground}
mkdir_status=$?

if [[ mkdir_status -ne 0 ]]; then
    echo "Failed to create playground '${playground_name}'"
    return 1
fi

printf "package main

import (
	\"fmt\"
)

func main() {
	fmt.Println(\"Hello, playground\")
}
" > ${new_playground}/main.go

code ${new_playground}
